### ISSUE TITLE
Read raspberrys internal temp

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/bryggio#36]
For performance monitoring. Perhaps some other stats as well

**Comment by JonathanFager** [comment]
$ vcgencmd measure_temp | egrep -o '[0-9]*\.[0-9]*'

**Comment by jackonelli** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=170112

**Comment by jackonelli** [comment]
https://docs.rs/dht22_pi/0.1.0/dht22_pi/
