### ISSUE TITLE
Set up webserver

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/bryggio#5]
DoD: Webserver running on either Raspberry or external computer which the raspberry then communicates to.

Investigate and decide upon webserver for serving and handling requests.

- [x] Serve startpage
- [x] Shared state between web server/brew backend
- [x] Well functioning API for all TODO's in 0.1.0 project

**Comment by jackonelli** [comment]
I have decided on a shared state based API for the communication between webserver and brewery backend.
It does not scale well but works perfectly for the static first version

**Comment by jackonelli** [comment]
Changed my mind again. Now it's back to thread safe mpsc channels. Works like a hoot.
