### ISSUE TITLE
dsb1820 read is slow

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/bryggio#50]
Seems weird. I don't think a manual `cat` read is slow. I do not have one at home to try it out

**Comment by JonathanFager** [comment]
Fixed?

**Comment by jackonelli** [comment]
Test: read manual from OS. (` cat /sys/bus/w1/devices/<address>/w1_slave`) and that is slow as well; the cause is not an internal bryggio bug.
The read can maybe be done faster by bitbanging but it is not really a problem, it was rather that I wanted to know the cause of the slowness.
