### ISSUE TITLE
Shutdown command

### ISSUE THREAD

**Issue by jackonelli** [BryggansBryggeri/bryggio#65]
We want to be able to make some clients cease and desist (e.g. a controller client).
This should be done with like a `command.stop.<id>` topic

External clients can of course choose not to heed these commands, which is fine.

**Comment by jackonelli** [comment]
This should be done with the request functionality.

**Comment by JonathanFager** [comment]
Isn't this now implemented?

**Comment by jackonelli** [comment]
> This should be done with the request functionality.

How would it reply when it is shut down, idiot?

> Isn't this now implemented?

Nope

**Comment by jackonelli** [comment]
Duplicate of #41
